version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "lefv"
    labels:
      - "dependencies"
      - "npm"
    groups:
      dev-dependencies:
        patterns:
          - "@babel/*"
          - "@types/*"
          - "eslint*"
          - "webpack*"
          - "jest*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "phaser*"
          - "lodash"
        update-types:
          - "patch"
    ignore:
      - dependency-name: "phaser"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"