blank_issues_enabled: true
contact_links:
    - name: 📖 Documentation
      url: https://github.com/gwicho38/myRPG/blob/master/README.md
      about: Read the documentation for guides and tutorials
    - name: 💬 Discussions
      url: https://github.com/gwicho38/myRPG/discussions
      about: Ask questions and discuss with the community
    - name: 🔒 Security Issue
      url: https://github.com/gwicho38/myRPG/security/advisories/new
      about: Report a security vulnerability privately
