name: Feature Request
description: Suggest a new feature or enhancement
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible.

    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description: Is your feature request related to a problem? Please describe.
          placeholder: I'm frustrated when...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: Describe the solution you'd like
          placeholder: I would like to see...
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternatives Considered
          description: Describe any alternative solutions or features you've considered
          placeholder: I also thought about...

    - type: dropdown
      id: component
      attributes:
          label: Component
          description: Which part of the game does this feature relate to?
          options:
              - Player/Character
              - Combat/Battle System
              - Inventory/Items
              - Dialog System
              - Map/Level Generation
              - UI/HUD
              - Save/Load System
              - Mobile Controls
              - Other
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature to you?
          options:
              - Low - Nice to have
              - Medium - Would improve experience
              - High - Critical for my use case
      validations:
          required: true

    - type: textarea
      id: usecase
      attributes:
          label: Use Case
          description: Describe your use case and how this feature would benefit users
          placeholder: This would help users...
      validations:
          required: true

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context, mockups, or examples about the feature request
