name: Build Multi-Platform

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:web
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: dist/

  build-desktop:
    needs: build-web
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: builds/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-web, build-desktop]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v6
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web-build/**/*
            desktop-*/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}